apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: af-back
spec:
  selector:
    app: backend-app
  ports:
    - protocol: "TCP"
      port: 8085
      targetPort: 80 # The port exposed by the service
  type: ClusterIP # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: nizarfarhane/af-front:1.0
          imagePullPolicy: Always
          ports:
          - containerPort: 80
